[time]
time_format = "%T"
format = "ðŸ•™ $time($style) "
style = "bright-white"
disabled = false

[character] # The name of the module we are configuring is 'character'
success_symbol = '[âžœ](bold green)' # The 'success_symbol' segment is being set to 'âžœ' with the color 'bold green'
